deployment:
  tasks:
    - export DEPLOYPATH=/home/yjfcorg/public_html/75
    - git submodule update --init --recursive
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
