deployment:
  tasks:
    - export DEPLOYPATH=/home/yjfcorg/public_html/75/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
